# Generated by Django 4.0 on 2022-03-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageapp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='user',
        ),
    ]
